// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteLogs(arg1) {
  return window['go']['main']['App']['DeleteLogs'](arg1);
}

export function DeleteProcess(arg1) {
  return window['go']['main']['App']['DeleteProcess'](arg1);
}

export function GetLogs(arg1) {
  return window['go']['main']['App']['GetLogs'](arg1);
}

export function GetProcesses() {
  return window['go']['main']['App']['GetProcesses']();
}

export function InsertProcess(arg1) {
  return window['go']['main']['App']['InsertProcess'](arg1);
}

export function OpenGithub() {
  return window['go']['main']['App']['OpenGithub']();
}

export function ProcessesReorder(arg1) {
  return window['go']['main']['App']['ProcessesReorder'](arg1);
}

export function RunProcess(arg1) {
  return window['go']['main']['App']['RunProcess'](arg1);
}

export function StopProcess(arg1) {
  return window['go']['main']['App']['StopProcess'](arg1);
}

export function UpdateProcess(arg1) {
  return window['go']['main']['App']['UpdateProcess'](arg1);
}
